

models:
  default_model: "distilbert-base-uncased-distilled-squad"   # Default model for Q&A (can be replaced)
  deepseek_model: "deepseek/deepseek-chat:free"  # DeepSeek model option

pipeline_stages:
  - load_data: "src.load_data.LoadDataStage"
  - clean_data: "src.clean_data.TransformStage"
  - qa_transform: "src.qa_transform.QATransformStage"

logging:
  log_file: "logs/pipeline.log"
  log_level: "INFO"

# Model handler configurations
qa_stage:
  model_name: "deepseek/deepseek-chat:free"  # Default Q&A model used in QATransformStage
  model_type: "deepseek"  # Can be "qa" (HuggingFace) or "deepseek" (OpenRouter)
  api_key: "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"  # If using DeepSeek through OpenRouter


